name: Webhook on push

on:
  push:
    branches:
        - master

jobs:
  webhook_examples:
    runs-on: ubuntu-latest
    steps:
      - name: Get datetime
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Shoko Server Webhook
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-color: 5809492
          embed-timestamp: ${{ steps.date.outputs.date }}
          embed-author-name: Shoko Server | New Daily Build
          embed-author-icon-url: https://raw.githubusercontent.com/${{ github.repository }}/master/.github/images/shoko.png
          embed-author-url: https://github.com/ShokoAnime/ShokoServer
          embed-description: |
            **Version**:`4.2.2.0-dev-abcdefg`

            Update by grabbing the latest daily from [our site](https://www.shokoanime.com/downloads/shoko-server), or through Docker using the `shokoanime/server:daily` tag!

            **Changes since last build**:
            Commit Message A
            Commit Message B
            Commit Message C
            Commit Message D
      - name: Shoko Server Webhook (Alternative)
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-color: 5809492
          embed-timestamp: ${{ steps.date.outputs.date }}
          embed-author-name: Shoko Server
          embed-author-icon-url: https://raw.githubusercontent.com/${{ github.repository }}/master/.github/images/shoko.png
          embed-author-url: https://github.com/ShokoAnime/ShokoServer
          embed-title: New Daily Build
          embed-description: |
            **Version**:`4.2.2.0-dev-abcdefg`

            Update by grabbing the latest daily from [our site](https://www.shokoanime.com/downloads/shoko-server), or through Docker using the `shokoanime/server:daily` tag!

            **Changes since last build**:
            Commit Message A
            Commit Message B
            Commit Message C
            Commit Message D
      - name: Shokofin Webhook
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-color: 9985983
          embed-timestamp: ${{ steps.date.outputs.date }}
          embed-author-name: Shokofin | New Unstable Build
          embed-author-icon-url: https://raw.githubusercontent.com/${{ github.repository }}/master/.github/images/jellyfin.png
          embed-author-url: https://github.com/ShokoAnime/Shokofin
          embed-description: |
            **Version**:`3.0.1.131` (`abcdefg`)

            Update your plugin using the latest [unstable manifest](https://raw.githubusercontent.com/ShokoAnime/Shokofin/master/manifest-unstable.json) or by downloading the release from [GitHub Releases](https://github.com/ShokoAnime/Shokofin/releases/tag/3.0.1.131) and installing it manually!

            **Changes since last build**:
            Commit Message A
            Commit Message B
            Commit Message C
            Commit Message D
      - name: Web UI Webhook
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-color: 7641851
          embed-timestamp: ${{ steps.date.outputs.date }}
          embed-author-name: Web UI | New Daily Build
          embed-author-icon-url: https://raw.githubusercontent.com/${{ github.repository }}/master/.github/images/webui.png
          embed-author-url: https://github.com/ShokoAnime/ShokoServer-WebUI
          embed-description: |
            **Version**:`2.1.0-dev.122`

            Update from the Web UI or click [here](https://github.com/ShokoAnime/Shoko-WebUI/releases/tag/v2.1.0-dev.122) to download!

            **Changes since last build**:
            Commit Message A
            Commit Message B
            Commit Message C
            Commit Message D
